---
title: "Project4"
name: Camille Cavicchio, Jared Steinberg, and Alain Perez
output: html_document
---

```{r, message=FALSE, echo=FALSE, warning=FALSE}
library(dbplyr)
library(mdsr)
library(RMySQL)
library(ggthemes)
library(USAboundaries)
library(sf)
library(maps)
library(mapproj)
library(ggplot2)
library(RColorBrewer)
library(ggplot2)
library(ggmap)
library(mapdata)
```

```{r, message=FALSE, echo=FALSE, warning=FALSE}
db<-dbConnect_scidb("fec")
```

```{r, message=FALSE, echo=FALSE, warning=FALSE, eval=FALSE}
dbListTables(db)
```
```{sql connection=db}
select * from candidates
limit 1,10
```

```{sql connection= db}
SELECT
  c.cand_id,
  c.cand_name,
  c.cand_party_affiliation,
  c.cand_election_yr,
  c.cand_office_state,
  c.cand_zip,
  b.transaction_dt, 
  sum(transaction_amt) AS total_trans
FROM candidates AS c 
LEFT JOIN contrib_com_to_cand AS b ON c.cand_id = b.cand_id 
WHERE c.cand_election_yr >= 2016 AND c.cand_id<=1 AND b.transaction_dt<=1
GROUP BY c.cand_id
order by c.cand_office_state
```

```{r, message=FALSE, echo=FALSE, warning=FALSE}
fec<-"SELECT
  c.cand_id,
  c.cand_name,
  c.cand_party_affiliation,
  c.cand_election_yr,
  c.cand_office_state,
  c.cand_zip,
  b.transaction_dt, 
  sum(transaction_amt) AS total_trans
FROM candidates AS c 
LEFT JOIN contrib_com_to_cand AS b ON c.cand_id = b.cand_id 
WHERE c.cand_election_yr >= 2016 AND c.cand_id<=1 AND b.transaction_dt<=1
GROUP BY c.cand_id
order by c.cand_office_state"
```


```{r, message=FALSE, echo=FALSE, warning=FALSE}
fecinfo<-db%>% dbGetQuery(fec) %>% collect()
fecinfo
```

```{r, message=FALSE, echo=FALSE, warning=FALSE}
pop<-read.csv("poop.csv")

pop <- pop %>%
  select(State, X2016, region) %>%
  rename(pop = "X2016") %>%
  mutate(pop = parse_number(pop))
pop

```

```{r}

fecinfo <- fecinfo %>%rename(State = 'cand_office_state',
                             ID='cand_id',
                             name='cand_name',
                             party='cand_party_affiliation',
                             year= 'cand_election_yr',
                             order= 'cand_zip',
                             transactions='total_trans') %>%
  select(-transaction_dt) %>%
  left_join(pop, by = "State")


```

```{r}

democrats_new <-fecinfo %>%
  filter(party == "DEM")
republicans_new <-fecinfo %>%
  filter(party == "REP")
democrats_new
republicans_new
```
```{r}

summed_dem <- aggregate(transactions ~ State, democrats_new, sum) 
summed_dem

democrats_new <- democrats_new%>%
  left_join(summed_dem, by = "State") %>%
  select(-transactions.x) %>%
  rename(transactions = transactions.y)
democrats_new <- democrats_new %>%
  mutate(proportion = (transactions / pop)) %>%
  mutate(new_proportion = log(proportion)) %>%
  arrange(desc(proportion))
democrats_new

```

```{r}

summed_rep <- aggregate(transactions ~ State, republicans_new, sum) 
summed_rep

republicans_new <- republicans_new%>%
  left_join(summed_rep, by = "State") %>%
  select(-transactions.x) %>%
  rename(transactions = transactions.y)
republicans_new <- republicans_new %>%
  mutate(proportion = (transactions / pop)) %>%
  mutate(new_proportion = log(proportion)) %>%
  arrange(desc(proportion))
republicans_new

```

```{r}
pop<-read.csv("poop.csv")

```


```{r}
usa <- map_data("usa") 
ggplot() + geom_polygon(data = usa, aes(x=long, y = lat, group = group)) + 
  coord_fixed(1.3)
```

```{r}
us <- ggplot(data = states, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")
```
 
```{r}

democratic_plot <- inner_join(states, democrats_new, by = "region")

left_elbow <- us + 
      geom_polygon(data = democratic_plot, aes(fill = new_proportion), color = "white") +
      geom_polygon(color = "black", fill = NA) +
      scale_fill_gradient2(low="lightsteelblue1", mid="royalblue1", high="navy", midpoint = -5, na.value = "grey50") + geom_curve(
    x = -122, xend = -117, y = 30, yend = 40,
    arrow = arrow(length = unit(0.3, "cm")), 
    curvature = -0.8
    ) +geom_text(
    x = -115, y = 28, 
    label = "Nevada has the \n highest porportion",
    colour = "black"
    )+
  ggtitle("USA")

left_elbow
```

```{r}

republican_plot <- inner_join(states, republicans_new, by = "region")

right_elbow <- us + 
      geom_polygon(data = republican_plot, aes(fill = new_proportion), color = "white") +
      geom_polygon(color = "black", fill = NA) + scale_fill_gradient2(low="white", mid="pink", high="red", midpoint = -5, na.value = "grey50") + geom_curve(
    x = -122, xend = -117, y = 30, yend = 40,
    arrow = arrow(length = unit(0.3, "cm")), 
    curvature = -0.8
    ) +geom_text(
    x = -115, y = 28, 
    label = "Nevada has the \n highest porportion",
    colour = "black"
    )+
  ggtitle("USA")

right_elbow
```
