---
title: "Project4"
name: Camille Cavicchio, Jared Steinberg, and Alain Perez
output: html_document
---

```{r, message=FALSE, echo=FALSE, warning=FALSE}
library(dbplyr)
library(mdsr)
library(RMySQL)
library(ggthemes)
library(USAboundaries)
library(sf)
library(maps)
library(mapproj)
library(ggplot2)
library(RColorBrewer)
```

```{r, message=FALSE, echo=FALSE, warning=FALSE}
db<-dbConnect_scidb("fec")
```

```{r, message=FALSE, echo=FALSE, warning=FALSE, eval=FALSE}
dbListTables(db)
```


```{sql connection= db}
SELECT
  c.cand_id,
  c.cand_name,
  c.cand_party_affiliation,
  c.cand_election_yr,
  c.cand_office_state,
  b.transaction_dt, 
  sum(transaction_amt) AS total_trans
FROM candidates AS c 
LEFT JOIN contrib_com_to_cand AS b ON c.cand_id = b.cand_id 
WHERE c.cand_election_yr >= 2016 AND c.cand_id<=1 AND b.transaction_dt<=1
GROUP BY c.cand_id
order by c.cand_office_state
```

```{r, message=FALSE, echo=FALSE, warning=FALSE}
fec<-"SELECT
  c.cand_id,
  c.cand_name,
  c.cand_party_affiliation,
  c.cand_election_yr,
  c.cand_office_state,
  b.transaction_dt, 
  sum(transaction_amt) AS total_trans
FROM candidates AS c 
LEFT JOIN contrib_com_to_cand AS b ON c.cand_id = b.cand_id 
WHERE c.cand_election_yr >= 2016 AND c.cand_id<=1 AND b.transaction_dt<=1
GROUP BY c.cand_id
order by c.cand_office_state"
```


```{r, message=FALSE, echo=FALSE, warning=FALSE}
fecinfo<-db%>% dbGetQuery(fec) %>% collect()
fecinfo
```

```{r, message=FALSE, echo=FALSE, warning=FALSE}
pop<-read.csv("statespopulation.csv")
pop <- pop %>%
  select(State, X2016) %>%
  rename(pop = "X2016") %>%
  mutate(pop = parse_number(pop))
pop

```

```{r}

fecinfo <- fecinfo %>%rename(State = 'cand_office_state',
                             ID='cand_id',
                             name='cand_name',
                             party='cand_party_affiliation',
                             year= 'cand_election_yr',
                             transactions='total_trans') %>%
  select(-transaction_dt) %>%
  left_join(pop, by = "State")


fecinfo
```


```{r}
summed_transactions <- aggregate(transactions ~ State, fecinfo, sum)

fecinfo <- fecinfo %>%
  left_join(summed_transactions, by = "State") %>%
  select(-transactions.x) %>%
  rename(transactions = 'transactions.y') %>%
  mutate(proportion = (transactions / pop)) %>%
  mutate(new_proportion = log(proportion)) %>%
  arrange(desc(proportion))

fecinfo

pop<-read.csv("statespopulation.csv")
#View(pop)


```

```{r}
#us <- us_states("2000-12-30")
#plot(st_geometry(us))
#title("U.S. state boundaries present day")
```


```{r}
map('state', fill = TRUE, col = palette())
```


```{r}
map('county', "nevada",  fill = TRUE, col = palette())
```



```{r}
if(require(mapproj)) 
data(unemp)
data(county.fips)

colors = c("#F1EEF6", "#D4B9DA", "#C994C7", "#DF65B0", "#DD1C77", "#980043")
unemp$colorBuckets <- as.numeric(cut(unemp$unemp, c(-12, -9, -7, -5, -3, -1, 1)))
leg.txt <- c("<2%", "2-4%", "4-6%", "6-8%", "8-10%", ">10%")
# align data with map definitions by (partial) matching state,county
# names, which include multiple polygons for some counties
cnty.fips <- county.fips$fips[match(map("county", plot=FALSE)$names,
county.fips$polyname)]
colorsmatched <- unemp$colorBuckets [match(cnty.fips, unemp$fips)]

map("state", col = colors[colorsmatched], fill = TRUE, resolution = 0,
lty = 0, projection = "polyconic")
title("unemployment by county, 2009")
legend("topright", leg.txt, horiz = TRUE, fill = colors)
```


```{r}
usa = st_as_sf(map('usa', plot = TRUE, fill = TRUE))
laea = st_crs("+proj=laea +lat_0=30 +lon_0=-95") # Lambert equal area
usa <- st_transform(usa, laea)
g = st_graticule(usa)
plot(st_geometry(g), axes = TRUE)

```

```{r}
plot(usa, graticule = TRUE, key.pos = NULL, axes = TRUE)
#thinkg about creating function for color that takes in a number from proportion and outputs a color (possibly using brewer pacakge)
```

```{r}
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)

usa <- map_data("usa") 
ggplot() + geom_polygon(data = usa, aes(x=long, y = lat, group = group)) + 
  coord_fixed(1.3)

ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + 
  coord_fixed(1.3) +
  guides(fill=FALSE)

nv_df <- subset(states, region == "nevada")
counties <- map_data("county")
nv_county <- subset(counties, region == "nevada")

nv_base <- ggplot(data = nv_df, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")

nv_base  + 
  geom_polygon(data = nv_county, fill = NA, color = "white") +
  geom_polygon(color = "black", fill = NA)
 
cacopa <- inner_join(nv_county, fecinfo, by = "state")
```
```{r}
library(stringr)
library(dplyr)


```




